site_name: Laboratorios de Programación
site_url: https://alejandra-437.github.io/POO/
docs_dir: docs

theme:
  name: material
  features:
    - navigation.sections # agrupa por secciones en la barra izquierda
    - navigation.expand # deja todo expandido
    - toc.integrate # mete el índice (ToC) de la página en la barra izquierd
nav:
  - Inicio: index.md
  - Laboratorio 1:
      - Introduccion: index.md
      - Que es POO: index.md#que-es-poo
      - Que es una clase: index.md#que-es-una-clase
      - Constructores: index.md#constructores
      - Modificadores de acceso: index.md#modificadores-de-acceso
      - Encapsulamiento: index.md#encapsulamiento
      - Uso de this y super: index.md#uso-de-this-y-super
      - Que es un objeto: index.md#que-es-un-objeto
      - Anexos: index.md#anexos
